# © AngelaMos | 2026
# report.ex

defmodule CertScout.Report do
  @moduledoc """
  Renders REPORT.md: a headline with the real totals and date, a scannable ranked
  table, then one section per top certification with its logo, mention count,
  share of postings, and a proportional bar. Logos resolve to a localized asset
  when present so the report renders with no network access on camera.
  """

  alias CertScout.Logos

  @bar_width 32
  @filled "█"
  @empty "░"

  @spec write(String.t(), map(), map()) :: :ok
  def write(output_dir, %{total: total, results: results}, meta) do
    assets_dir = Path.join(output_dir, "assets")
    top = Enum.take(results, meta.top_n)
    max = top |> List.first(%{count: 0}) |> Map.fetch!(:count)

    content =
      Enum.join([header(total, meta), table(top), sections(top, total, max, assets_dir), footer(meta)], "\n")

    File.write!(Path.join(output_dir, "REPORT.md"), content)
  end

  defp header(total, meta) do
    """
    # Cybersecurity Certification Demand

    ### #{number(meta.total_scraped)} job postings scanned on #{Date.to_iso8601(meta.generated_on)}

    From those, **#{number(total)}** were isolated as cybersecurity roles across #{number(meta.companies)} employers.
    Every number below is the real count of postings whose full text names the certification.
    Data sources: #{Enum.join(meta.sources, ", ")}.

    ---
    """
  end

  defp table(top) do
    rows =
      top
      |> Enum.with_index(1)
      |> Enum.map_join("\n", fn {r, rank} ->
        "| #{rank} | #{r.cert.name} | #{r.cert.issuer} | #{number(r.count)} | #{r.percent}% |"
      end)

    """
    ## Top #{length(top)} certifications in demand

    | Rank | Certification | Issuer | Postings | Share |
    |-----:|---------------|--------|---------:|------:|
    #{rows}

    ---
    """
  end

  defp sections(top, total, max, assets_dir) do
    top
    |> Enum.with_index(1)
    |> Enum.map_join("\n", fn {r, rank} -> section(r, rank, total, max, assets_dir) end)
  end

  defp section(r, rank, total, max, assets_dir) do
    pct = r.percent

    """
    ## #{rank}. #{r.cert.name}

    <img src="#{logo(r.cert.slug, assets_dir)}" alt="#{r.cert.name}" height="84">

    **#{number(r.count)}** of #{number(total)} cybersecurity postings — **#{pct}%**

    `#{bar(r.count, max)}`

    Issuer: #{r.cert.issuer}

    ---
    """
  end

  defp footer(meta) do
    """
    Search terms: #{Enum.join(meta.search_terms, ", ")}

    Generated by CertScout. Raw data in `data/`.
    """
  end

  defp logo(slug, assets_dir) do
    file = "#{slug}.#{Logos.extension(slug)}"

    if File.exists?(Path.join(assets_dir, file)) do
      "assets/#{file}"
    else
      Logos.url(slug)
    end
  end

  defp bar(_count, 0), do: String.duplicate(@empty, @bar_width)

  defp bar(count, max) do
    filled = round(count / max * @bar_width)
    String.duplicate(@filled, filled) <> String.duplicate(@empty, @bar_width - filled)
  end

  defp number(n) do
    n
    |> Integer.to_string()
    |> String.reverse()
    |> String.replace(~r/(\d{3})(?=\d)/, "\\1,")
    |> String.reverse()
  end
end
